### ISSUE TITLE
Consistency of "email" translation

### ISSUE THREAD

**Issue by sebastiendelorme** [mrflos/q2a-lang-fr#14]
Currently, there is a lot of various and different translation for "email" :
- email
- e-mail
- courriel
- adresse électronique
- etc.

I'd like to make it more consistent. 
What do you think of using "e-mail" for the French version?

- "courriel" and "adresse électronique" doesn't seem to be well known by everyone
- "email" is read "[émail](https://fr.wikipedia.org/wiki/%C3%89mail_(verre))" by a lot of text-to-speech used by blind people, dyslexics, etc.

**Comment by mrflos** [comment]
ok for "e-mail", your arguments are good!
